# Generated by Django 3.2.6 on 2021-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
