# Generated by Django 3.2.6 on 2021-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Polkadots count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fontawesome User icon name'),
        ),
    ]
