# Generated by Django 3.2.6 on 2021-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
