# Generated by Django 3.2.6 on 2021-12-25 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 12, 25, 8, 29, 12, 850127, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
