# Generated by Django 3.2.4 on 2022-01-29 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 1, 29, 17, 53, 44, 758063, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
